# This file configures the GAE docker instance and environment.
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml

# The default service is deployed to: https://openag-cloud-v1.appspot.com/
service: default

runtime: nodejs
env: flex

# in node, use process.env.<name> to get these
env_variables:
  PROJECT_ID: openag-cloud-v1
  BQ_USER_DATASET: openag_private_webui
  BQ_USER_TABLE: user
  BQ_RECIPE_TABLE: rec
  BQ_CMD_TABLE: cmd
  BQ_STATUS_TABLE: status
  BQ_DATA_DATASET: test
  BQ_VALUE_TABLE: vals

  PUBSUB_TOPIC: projects/openag-cloud-v1/topics/commands

  # The App Engine Memcache service is currently in alpha.
  # When it goes live for the FLEX env, try it.  
  # (it is live for the standard env, but we don't want to use that env)
  # USE_GAE_MEMCACHE: 1

  MEMCACHE_URL: memcached-13909.c1.us-east1-2.gce.cloud.redislabs.com:13909
  # We are using a Memcached server with SASL authentiation enabled,
  # this is the specified Redis user for this DB/bucket (at the above
  # endpoint).
  MEMCACHE_USERNAME: rbaynes@gmail.com
  MEMCACHE_PASSWORD: Il0veRedis

