service: pubsub
runtime: custom
env: flex
runtime_config:
  # You can also specify 2 for Python 2.7
  python_version: 3

env_variables:
  PROJECT_ID: openag-v1
  PUBSUB_TOPIC: projects/openag-cloud-v1/topics/environmental-data
  BQ_DATASET: test
  BQ_TABLE: vals
  BQ_USER_DATASET: openag_private_webui
  BQ_STATUS_TABLE: status
  BQ_COMMAND_TABLE: cmd
