service: pubsub
runtime: custom
env: flex
runtime_config:
  # You can also specify 2 for Python 2.7
  python_version: 3

env_variables:
  PROJECT_ID: openag-v1
  PUBSUB_TOPIC: projects/openag-v1/topics/device-events
  #BQ_DATASET: test
  #BQ_TABLE: vals
